{
 "title": "OT Process Overview",
 "tags": [
  "ot",
  "ics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Tank level %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "otlab_plc_tank_level_percent" }
   ]
  },
  {
   "title": "Pressure bar",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "otlab_plc_pressure_bar" }
   ]
  },
  {
   "title": "Pump speed %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "otlab_plc_pump_speed_percent" }
   ]
  },
  {
   "title": "Safe state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "otlab_plc_safe_state" }
   ]
  }
 ]
}