route:
  receiver: console
  group_by: [alertname, service]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h

receivers:
  - name: console

inhibit_rules:
  - source_matchers: ['severity="critical"']
    target_matchers: ['severity="warning"']
    equal: [service]
