apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-api
  namespace: checkout
  labels:
    team: engineering
    cost-center: cc-410
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: checkout-api
  template:
    metadata:
      labels:
        app: checkout-api
        team: engineering
        cost-center: cc-410
        environment: production
    spec:
      containers:
        - name: api
          image: nginx:1.29-alpine
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: checkout-api
  namespace: checkout
  labels:
    team: engineering
    cost-center: cc-410
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: checkout-api
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-agent
  namespace: platform-system
  labels:
    team: platform
    cost-center: cc-100
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform-agent
  template:
    metadata:
      labels:
        app: platform-agent
        team: platform
        cost-center: cc-100
        environment: production
    spec:
      containers:
        - name: agent
          image: nginx:1.29-alpine
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
