apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-hostpath
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: hostpath-is-forbidden
      match:
        any:
          - resources:
              kinds:
                - Deployment
      validate:
        message: hostPath volumes are forbidden.
        pattern:
          spec:
            template:
              spec:
                "=(volumes)":
                  - "X(hostPath)": "null"
